development:
  user: fedoraAdmin
  password: fedoraAdmin
 # url: http://132.236.27.77:8080/fcrepo-webapp-4.4.0/rest
  url: http://hydraedit-dev.library.cornell.edu:8080/fedora/rest
  base_path: /devsolr410
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /prod
