development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://hydradev.library.cornell.edu:8080/fcrepo-webapp-4.4.0/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://hydradev.library.cornell.edu:8080/fcrepo-webapp-4.4.0/rest/
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://hydradev.library.cornell.edu:8080/fcrepo-webapp-4.4.0/rest/
  base_path: /prod
