# This is a sample config file that points to a solr server for each environment
development:
  url: http://hydraedit-dev.library.cornell.edu:8983/solr/digitalcollections
  #url: http://ouexhibits-dev.solr.library.cornell.edu/solr/collection1
test:
  url: http://hydraedit-dev.library.cornell.edu:8983/solr/digitalcollections
production:
 # url: http://your.production.server:8080/bl_solr/core0
#  url: http://jrc88.solr.library.cornell.edu/solr/collection1
#  url: http://ouexhibits-dev.solr.library.cornell.edu/solr/collection1
  url: http://hydradev.library.cornell.edu:8983/solr/digitalcollections
test:
