# This is a sample config file that points to a solr server for each environment
development:
 # url: http://hydrastg.library.cornell.edu/solr/common_core
   url: http://jrc88.solr.library.cornell.edu/solr/digitalcollections_dev
test:
  #url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
   url: http://jrc88.solr.library.cornell.edu/solr/digitalcollections_dev
production:
  url: http://your.production.server:8080/bl_solr/core0
